import{useEffect,useMemo,useState}from"react";
const api=async(p,o={})=>{let t=localStorage.getItem("token"),h={"Content-Type":"application/json",...(o.headers||{})};if(t)h.Authorization=`Bearer ${t}`;let r=await fetch(p,{...o,headers:h}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||"Request failed");return d};
export default function App(){const[f,setF]=useState([]),[c,setC]=useState([]),[o,setO]=useState([]),[u,setU]=useState(()=>JSON.parse(localStorage.getItem("user")||"null")),[v,setV]=useState("menu"),[q,setQ]=useState(""),[m,setM]=useState("");
const load=()=>api("/api/foods").then(setF);const loadO=()=>u&&api("/api/orders").then(setO);useEffect(()=>{load().catch(e=>setM(e.message))},[]);useEffect(()=>{loadO()},[u]);
const ff=useMemo(()=>f.filter(x=>(x.name+" "+x.category).toLowerCase().includes(q.toLowerCase())),[f,q]);const add=x=>setC(z=>{let a=z.find(i=>i.id===x.id);return a?z.map(i=>i.id===x.id?{...i,n:i.n+1}:i):[...z,{...x,n:1}]});const total=c.reduce((s,x)=>s+x.price*x.n,0);
async function order(){if(!u){setV("auth");return}try{let r=await api("/api/orders",{method:"POST",body:JSON.stringify({items:c.map(x=>({food_id:x.id,quantity:x.n}))})});setC([]);loadO();setV("orders");setM(`Order #${r.order_id} placed`)}catch(e){setM(e.message)}}
function logout(){localStorage.clear();setU(null);setV("menu")}
return <><header><b onClick={()=>setV("menu")}>🍔 QuickEats</b><nav><button onClick={()=>setV("menu")}>Menu</button><button onClick={()=>setV("cart")}>Cart ({c.reduce((s,x)=>s+x.n,0)})</button>{u&&<button onClick={()=>setV("orders")}>Orders</button>}{u?.role==="admin"&&<button onClick={()=>setV("admin")}>Admin</button>}{u?<button onClick={logout}>Logout</button>:<button className="p" onClick={()=>setV("auth")}>Login</button>}</nav></header><main>{m&&<div className="msg">{m}</div>}{v==="menu"&&<><section className="hero"><div><small>FAST • FRESH • SIMPLE</small><h1>Delicious food,<br/>delivered with ease.</h1><p>Real React + Flask + PostgreSQL food ordering.</p></div><span>🍕</span></section><input className="search" placeholder="Search food..." value={q} onChange={e=>setQ(e.target.value)}/><section className="grid">{ff.map(x=><article className="card" key={x.id}><div className="emoji">🍛</div><small>{x.category}</small><h3>{x.name}</h3><p>{x.description}</p><footer><b>₹{x.price}</b><button className="p" onClick={()=>add(x)}>Add</button></footer></article>)}</section></>}{v==="cart"&&<section className="panel"><h2>Cart</h2>{c.map(x=><div className="row" key={x.id}><b>{x.name}</b><span><button onClick={()=>setC(c.map(i=>i.id===x.id?{...i,n:i.n-1}:i).filter(i=>i.n>0))}>−</button>{x.n}<button onClick={()=>setC(c.map(i=>i.id===x.id?{...i,n:i.n+1}:i))}>+</button></span><b>₹{x.price*x.n}</b></div>)}<h3>Total ₹{total}</h3><button className="p" onClick={order}>Place Order</button></section>}{v==="orders"&&<section className="panel"><h2>My Orders</h2>{o.map(x=><div className="row" key={x.id}><span><b>Order #{x.id}</b><small>{x.status}</small></span><b>₹{x.total_amount}</b>{["Pending","Confirmed"].includes(x.status)&&<button onClick={async()=>{await api(`/api/orders/${x.id}`,{method:"DELETE"});loadO()}}>Cancel</button>}</div>)}</section>}{v==="auth"&&<Auth onLogin={x=>{setU(x);setV("menu")}}/>}{v==="admin"&&u?.role==="admin"&&<Admin foods={f} refresh={load}/>}</main><footer>QuickEats • 3-Tier DevOps Application</footer></>}
function Auth({onLogin}){let[r,setR]=useState(false),[f,setF]=useState({name:"",email:"",password:""}),[e,setE]=useState("");async function go(x){x.preventDefault();try{let d=await api("/api/auth/"+(r?"register":"login"),{method:"POST",body:JSON.stringify(f)});if(r){setR(false);setE("Registered. Login now.")}else{localStorage.setItem("token",d.token);localStorage.setItem("user",JSON.stringify(d.user));onLogin(d.user)}}catch(x){setE(x.message)}}return <section className="panel auth"><h2>{r?"Register":"Login"}</h2><p>{e}</p><form onSubmit={go}>{r&&<input required placeholder="Name" onChange={x=>setF({...f,name:x.target.value})}/>}<input required type="email" placeholder="Email" onChange={x=>setF({...f,email:x.target.value})}/><input required type="password" placeholder="Password" onChange={x=>setF({...f,password:x.target.value})}/><button className="p">{r?"Register":"Login"}</button></form><button onClick={()=>setR(!r)}>{r?"Login":"Create account"}</button><small>Admin: admin@quickeats.local / admin123</small></section>}
function Admin({foods,refresh}){let[f,setF]=useState({name:"",category:"Biryani",description:"",price:""});async function add(){await api("/api/foods",{method:"POST",body:JSON.stringify(f)});setF({name:"",category:"Biryani",description:"",price:""});refresh()}return <section className="panel"><h2>Admin Food CRUD</h2><div className="admin">{["name","category","description","price"].map(k=><input key={k} placeholder={k} value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/>)}<button className="p" onClick={add}>Add Food</button></div>{foods.map(x=><div className="row" key={x.id}><span>{x.name} — ₹{x.price}</span><button onClick={async()=>{await api(`/api/foods/${x.id}`,{method:"DELETE"});refresh()}}>Delete</button></div>)}</section>}
